script: bash ./deploy.sh
language: node_js
node_js:
- '5'
env:
  global:
  - GH_REF: github.com/websemanticsio/media.git
  - secure: HzU/tPVYA1BU6J4gKj2bQoV6l6nm6SmpcrWWCG1Jwm6g10WfHsVUR45YczFMKucEPsf9X36c/yIs8JBKRCqk4KSDfansO13f4NZrG8DnAUVtJrX1K2aSHjJw91HBtL/eZmpkLuepJ1iBpxBTljcpy3h411OBUzlsbclWWsKJg00o/dpYLeBgIcFBt9sFqEnnzx5iaIW9R1L62+GdQ20ISaQZKytcuX2cZLx8tlUjJjBSw93ggXsM7BiWE+STLZ6fH/5jXBKXQK3BpWWwU/e2+wACMeF3IiprmZgRl56bww+qWTjKN1jrQvdFZyLTRoE2Y6yPZiO82cI2HqomZbfZWGKh698T1yREbJhnRKpdi7YVJzyaV5II6zgCY0j8nTrtssYoWTVado3i3qQjj5vljlcFAEbfItgm/bKCIuhoIgQ/y/sxDcLvGoBwOehUkxnDzEX9ldqj309t17fbeO+tgfyA+/tFl83w2reJUczJFb/uL9M2ZBwWIUHQwWWSZ92PdQRxmrGG/qdgsQ0L34aHkDSGbv2RWR4xZRqvDZjYzMDxvkkup7n/od7oRo5DV2oEmvELeqHKbxF+16EUs/qZoNZv5MXVApHciOtfFcwR0YAafFjdAdYEUik30dj2hSYCjuaKOnt9cfWjCysggUPSP+w/UFBR5GAe2yJNlc1TH6o=
