script: bash ./deploy.sh
language: node_js
node_js:
- '5'
env:
  global:
  - GH_REF: github.com/websemanticsio/media.git
  - secure: GdEqofURs2DYsOIrKYg6OTILMb8xGSbmK4pLZ3PZW6fdnhAUkXeiWycwC1n7QPmC33R3eiciAq12c2yl1oMOhbgxLRRME+RC4Iw/GWvSGEDEI6gQGKyHRuGu6R7JCXh8Qd9UYgcBPa5gefykMY7x14cpBYX6byXcLddobW/gOd5hcGAfkd0GhXzorWbKosSvK0R1pZZm7djDVDOH8gqZYwkzfOr0Yer0saPr0mkJjBKsQvbsDzZ6FtxMbbA0mmuPmfciz+xf2WlZvmlIvg5jfoMAYaRpYzi3AV6ZtbAARvnIOtJAoJIJq4+LLQqOwEhaKbn4QKIlDKNx6vD53ccPnJRJIn0hPAJLzocnAtNvrExWkm2Dj1fa/eMmNT4wc8vYriP5UNd7SF812sUIfCTJtRvf1aow5CqvIE6HavLNEJk5DVgsYwL9niXc9GR4howinzroX/Kz0lBfZxuWJRcir25WZkk5JcQpWlP0jts+4w7rTK+LXrCAu8DjWCTA4g7EaM/q1ajTku8AhPzhfBA6qcqWOyFAbkfyxpglq5zEYLQQFDwdhmHuO7eWWklsNbxXtzCaO2YMgklIoJRCrift0Qf4aaK2lzkRGx+UT9nNFYko1x6szO6ntdznw7sqxa40hn4Gh5KSABF8BRh0q9lrpjZhT29fK/1J6l1Dl+VO5iM=
